version: '3'

services:

  db:
    container_name: db
    image: postgres:latest
    restart: unless-stopped
    hostname: db
    ports: 
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_USER}
    networks: 
      - api

  pgadmin:
    container_name: pg_admin
    image: dpage/pgadmin4
    restart: unless-stopped
    hostname: pgadmin
    ports:
      - "4444:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - api

networks:
  api:
    driver: bridge